### ISSUE TITLE
No valid binary found for sga

### ISSUE THREAD

**Issue by ycl6** [bonsai-team/matam#38] opened 2017-09-17 12:07 UTC
MATAM spill out these messages complaining not finding the sga binary.
```
INFO - Graph compaction & Components identification terminated in 63.3342 seconds wall time
INFO - Compressed graph: 472 components

INFO - === LCA labelling ===
INFO - LCA labelling terminated in 7.3417 seconds wall time

INFO - === Contigs assembly ===
INFO - Save components to fastq files
INFO - Assemble components
No valid binary found for sga
No valid binary found for sga
No valid binary found for sga
No valid binary found for sga
No valid binary found for sga
...
```
I export `$MATAM_HOME/sga/src/bin` to $PATH but that doesn't help.

**Comment by ppericard** [comment] 2017-09-17 12:13
Hi @ycl6, how did you get MATAM ? Through conda or did you compile it yourself ?
If you compiled it from the source code, can you send us the trace from the `./build.py` script ?

In any case, if you have difficulties running MATAM from the source code, we really encourage you to get it through conda, which makes way easier dealing with dependencies and you wont need to compile it.

**Comment by ycl6** [comment] 2017-09-17 23:58
Hi @ppericard 
I install MATMA via github source. I found the solution. the sga binary MATAM is looking for is not located in `$MATAM_HOME/sga/src/bin` but is actually in `$MATAM_HOME/sga/src/SGA`. Therefore I add that to $PATH too and MATAM is able to complete the job. Thanks.

**Comment by ppericard** [comment] 2017-09-18 07:20
@loic-couderc , can you check this is not a bug ?

**Comment by loic-couderc** [comment] 2017-09-18 09:29
Hi @ycl6, with the version v1.3.0 of MATAM, if the `./build.py` script terminated with no errors which means you have this message at the end of the trace:
```text
2017-09-18 10:09:07,300 - INFO - -- MATAM building complete --
2017-09-18 10:09:07,300 - DEBUG - Building completed in 377.46 seconds
2017-09-18 10:09:07,300 - DEBUG - MATAM building went well. Program executables can be found in MATAM bin directory: ...
```

Then MATAM should find the SGA binary into `$MATAM_HOME/sga/src/SGA` without any modification of the PATH.
Can you send us the the trace from the `./build.py` script?

**Comment by ycl6** [comment] 2017-09-19 23:59
Hi @loic-couderc 

I reset $PATH to its original state and reinstall `matam` but can't reproduce the error anymore. Don't know what happen during my initial build, but all is fine now

```
2017-09-19 21:03:18,105 - INFO - -- MATAM building complete --
2017-09-19 21:03:18,105 - DEBUG - Building completed in 520.30 seconds
2017-09-19 21:03:18,105 - INFO - MATAM building went well. Program executables can be found in MATAM bin directory: /home/ycl6/tools/matam/bin

Namespace(target='build')
```

**Comment by loic-couderc** [comment] 2017-09-20 08:40
As we cannot reproduce the bug, I close this issue.

**Closed as completed by loic-couderc** 2017-09-20 08:40 UTC
Labels: wontfix, user-error
